-- 코드를 입력하세요
SELECT 
P.PRODUCT_CODE,
SUM(SALES_AMOUNT) * P.PRICE AS SALES
FROM OFFLINE_SALE OS
INNER JOIN PRODUCT P
ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES desc, P.PRODUCT_CODE asc